version: '3'

services:

  mc1:
    container_name: mc1
    hostname: mc1
    build:
      context: ./mc1
      dockerfile: Dockerfile
    ports:
     - 9000:9000
    restart: unless-stopped
    depends_on:
      - maria_db
      - jaeger-allinone
    environment:
      JAEGER_AGENT_HOST: jaeger-allinone

  mc2:
    container_name: mc2
    hostname: mc2
    build:
      context: ./mc2
      dockerfile: Dockerfile
    ports:
     - 9010:9010
    restart: unless-stopped
    depends_on:
      - maria_db
      - jaeger-allinone
    environment:
      JAEGER_AGENT_HOST: jaeger-allinone

  mc3:
    container_name: mc3
    hostname: mc3
    build:
      context: ./mc3
      dockerfile: Dockerfile
    ports:
     - 9020:9020
    restart: unless-stopped
    depends_on:
      - maria_db
      - jaeger-allinone
    environment:
      JAEGER_AGENT_HOST: jaeger-allinone

  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:SASL_PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
    depends_on:
      - zookeeper
    volumes:
      - ./:/etc/kafka  

  maria_db:
    image: "mariadb:10.5.8"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: invite_test_task
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword

  jaeger-allinone:
    image: jaegertracing/all-in-one:1.7
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411

