server.port: 9000

application:
  sendingIntervalInSecs: 3
  jaeger.serviceName: mc1
  websocket:
    mc2Endpoint: ws://mc2:9010/chat
    topicName: /topic/messages
    destination: /app/chat/java

spring.datasource:
  url: jdbc:mariadb://maria_db:3306/invite_test_task
  username: user
  password: password
  initialization-mode: always

spring.jpa.hibernate.ddl-auto: update